### ISSUE TITLE
progress bar does not seem to work correctly

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/anatomy#10]
there is a wrong proportion of green (50) and yellow (113)
![progres- zelena 50 saha odhadem do ctvrtiny zlute 113](https://cloud.githubusercontent.com/assets/115575/10598005/f9b14a4e-76f4-11e5-8d63-cb2958568bdf.png)

**Comment by papousek** [comment]
How is it fixed?

**Comment by slaweet** [comment]
By showing `number_of_practiced_flashcards` not `number_of_nonmastered_practiced_flashcards`
https://github.com/adaptive-learning/anatomy/commit/556d9b079d6c864a8467b91e0f6e4a73cdedb8af

**Comment by marekcierny** [comment]
Although this helped, I am afraid it is still not perfect:
There seems to be some inconsistency between the horizontal progress bar
and the circular one. (see attachement: horizontal has no yellow, although
I would expect it to be an average of all circular bars, which all have
some yellow).

**Comment by marekcierny** [comment]
![progress bar](https://cloud.githubusercontent.com/assets/15195345/11169747/eca3c52a-8b85-11e5-847e-56f650840be9.png)
