### ISSUE TITLE
Subscriptions client-side

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/anatomy#32]
- [x] setup GoPay 
- [x] specify subscription plans
- [x] display subscriptions in user profile
- [x] dislpay subscription plans
- [x] popup offering subscription
- [x] subscribe workflow for logged in user
- [x] subscribe workflow for anonymous user
- [x] disable access to /practice/relations/, redirect /practice/ to /practice/images for not subscribed users
- [x] add subscribed flag to subscriptionService
- [x] reload page on login
- [x] handle 100% discount code
- [x] deploy to production with hidden menu item
- [x] update relations data from znackuj.anatom.cz
- [x] set active subscription on production for testing
- [x] critical bugs reported by Marek in spreasheet (fix typeahead filtering)

**Comment by papousek** [comment]
Sample data for subscriptions: https://github.com/adaptive-learning/proso-apps/blob/master/testproject/test_data/subscription/plans.json

Command to load data for subscriptions: `./manage.py load_subscription_plans`
