### ISSUE TITLE
UI připomínky od Terky

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/anatomy#34]
Ukazoval jsem po dlouhé době Terce Anatoma (konkrétně jsem ji ukazoval otázky na souvislosti). Její reakce byla: "Je to super, ale je to hnusné."

Spousta jejích připomínek dávala smysl, tak tady je shrnutí:

![anatom-ui](https://cloud.githubusercontent.com/assets/115575/17606336/54efb2a6-601f-11e6-8c17-fe0c063b134e.png)

**Comment by slaweet** [comment]
Asi budu potřebovat slyšet tu původní verzi, protože ta shrnutá mi úplně smysl nedává. Souhlasím s myšlenkou "je to hnusné", jen nevím **proč** zrovna tyhle změny to spraví.

**Comment by papousek** [comment]
Začalo to tím, že Nastavení (ozubené kolečko) není součástí otázky. Potom pozorování, že "Nevím" je vlastně další možnost a že mezi touto "další možností" a zbytkem je tlačítko "Pokračovat".

Předpokládám, že ten dojem trochu kazí i ten otazník na novém řádku.
