### ISSUE TITLE
Wrong correctness detection?

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/anatomy#35]
![anatom-bug](https://cloud.githubusercontent.com/assets/115575/17614679/697e0260-6068-11e6-92c6-4c0f87d4f9d4.png)

**Comment by slaweet** [comment]
Looking into http://znackuj.anatom.cz/relations/ both options are correct. Should the server ask such questions?

**Comment by papousek** [comment]
ok

**Comment by papousek** [comment]
I will fix it in case of multiple-choice questions. Is it already handled in case of open questions with auto complete?

**Comment by papousek** [comment]
Multiple-choice questions fixed.
