### ISSUE TITLE
Enable custom config for subscribers

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/anatomy#37]
UI that allows to change:
- [x] set length
- [x] target difficulty
- [x] no-wiriting/open/multiple-choice questions
- [ ] turn off reference questions in no-writing condition
- [ ] change reference questions when set length is changed

**Comment by papousek** [comment]
Properties are:
1. set length: `proso_models.practice.set_length` (it is necessary to set also `proso_models.random_test.nth` to the same number, or -1 to disable reference questions)
2. target_difficulty: `item_selector.parameters.target_probability`
3. question type:
   - no-open: `proso_models.option_selector.parameters.allow_zero_options: false`
   - no-writing: `proso_models.option_selector.parameters.allow_zero_options_restriction: true`

**Comment by slaweet** [comment]
An initial version implemented:
https://staging.anatom.cz/settings/
Known problems:
- [x] Values are saved (checked in [0]) but after reload the form shows the default values again. I don't see why, I use get_global_config() (in views.py [1]) and it doesn't contain the new values.

[0] https://staging.anatom.cz/common/config/
[1] https://github.com/adaptive-learning/anatomy/blob/master/anatomy/views.py#L76

**Comment by papousek** [comment]
I will investigate it.
