### ISSUE TITLE
From Radovan: allow more advance filtering for practicing

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/anatomy#4]
e.g. Svaly a kosti horni koncetiny

**Comment by papousek** [comment]
How is it implemented?

**Comment by papousek** [comment]
Oh, I see. Cool.

**Comment by slaweet** [comment]
Done in  https://github.com/adaptive-learning/anatomy/commit/563a015668fc74c23da7a507075c29843da5873f and https://github.com/adaptive-learning/anatomy/commit/5e5ea85cc5f1ac52ae8e0e545fefb092d395df7d
