### ISSUE TITLE
Set up other payment options in gopay

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/anatomy#49]

**Comment by papousek** [comment]
I am not sure, how to add "online bankovní tlačítka" method (it is not mentioned in docs: https://doc.gopay.com/cs/#payment_instrument).

**Comment by slaweet** [comment]
Looks like they have incomplete docs and we need to open a support ticket:
https://help.gopay.com/cs/ticket/create

**Comment by papousek** [comment]
Added: online bank transfer and paypal
