### ISSUE TITLE
Check foramina

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/anatomy#59]
http://znackuj.anatom.cz/relations/List_of_foramina_of_the_human_body

**Comment by marekcierny** [comment]
Víťo, nejde mi tlačítko [+] pro přídání cévy nebo nervu u foramin, kde není žádná nápověda z Wikipedie, např:  foramen infraorbitale, supraorbital foramen , foramen cecum, foramina of cribriform plate, foramen incisivum. 
Můžeš se na to prosím podívat, abych to mohl doplnit?  @slaweet @

**Comment by slaweet** [comment]
Tlačítko [+] jsem opravil, Marku

**Comment by marekcierny** [comment]
Super, díky, moc!
Doplnil jsem to a zkontroloval.
