### ISSUE TITLE
Formulate questions for "foramina"

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/anatomy#60]

**Comment by marekcierny** [comment]
Done at [drive / Anatomie online / otazky na souvislosti](https://docs.google.com/spreadsheets/d/1OJ81d-4eqeAQiplTNRWFE91M7ozBGV5Yw57pZ6R6STA/edit#gid=0).
Začal bych jednoduchými 7 otázkami.
Kombinované otázky můžeme později.
